// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// App is the predicate function for app builders.
type App func(*sql.Selector)

// Media is the predicate function for media builders.
type Media func(*sql.Selector)

// Operator is the predicate function for operator builders.
type Operator func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
