// Code generated by entc, DO NOT EDIT.

package media

import (
	"time"
)

const (
	// Label holds the string label denoting the media type in the database.
	Label = "media"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeleteAt holds the string denoting the delete_at field in the database.
	FieldDeleteAt = "delete_at"
	// FieldHash holds the string denoting the hash field in the database.
	FieldHash = "hash"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldAppID holds the string denoting the app_id field in the database.
	FieldAppID = "app_id"
	// FieldSn holds the string denoting the sn field in the database.
	FieldSn = "sn"
	// FieldOrgFileName holds the string denoting the org_file_name field in the database.
	FieldOrgFileName = "org_file_name"
	// FieldFileName holds the string denoting the file_name field in the database.
	FieldFileName = "file_name"
	// FieldSize holds the string denoting the size field in the database.
	FieldSize = "size"
	// FieldMime holds the string denoting the mime field in the database.
	FieldMime = "mime"
	// FieldExt holds the string denoting the ext field in the database.
	FieldExt = "ext"
	// FieldRefCount holds the string denoting the ref_count field in the database.
	FieldRefCount = "ref_count"
	// FieldLevel holds the string denoting the level field in the database.
	FieldLevel = "level"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldReasonType holds the string denoting the reason_type field in the database.
	FieldReasonType = "reason_type"
	// FieldSavePath holds the string denoting the save_path field in the database.
	FieldSavePath = "save_path"
	// FieldFullPath holds the string denoting the full_path field in the database.
	FieldFullPath = "full_path"
	// FieldIsEncrypted holds the string denoting the is_encrypted field in the database.
	FieldIsEncrypted = "is_encrypted"
	// FieldReason holds the string denoting the reason field in the database.
	FieldReason = "reason"
	// FieldOutUserID holds the string denoting the out_user_id field in the database.
	FieldOutUserID = "out_user_id"
	// FieldCompanyID holds the string denoting the company_id field in the database.
	FieldCompanyID = "company_id"
	// Table holds the table name of the media in the database.
	Table = "medias"
)

// Columns holds all SQL columns for media fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeleteAt,
	FieldHash,
	FieldUserID,
	FieldAppID,
	FieldSn,
	FieldOrgFileName,
	FieldFileName,
	FieldSize,
	FieldMime,
	FieldExt,
	FieldRefCount,
	FieldLevel,
	FieldType,
	FieldStatus,
	FieldReasonType,
	FieldSavePath,
	FieldFullPath,
	FieldIsEncrypted,
	FieldReason,
	FieldOutUserID,
	FieldCompanyID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultRefCount holds the default value on creation for the "ref_count" field.
	DefaultRefCount int
	// DefaultLevel holds the default value on creation for the "level" field.
	DefaultLevel int
	// DefaultType holds the default value on creation for the "type" field.
	DefaultType int
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus int
	// DefaultReasonType holds the default value on creation for the "reason_type" field.
	DefaultReasonType int
	// DefaultIsEncrypted holds the default value on creation for the "is_encrypted" field.
	DefaultIsEncrypted bool
	// DefaultReason holds the default value on creation for the "reason" field.
	DefaultReason string
)
