// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package errors

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsErrReasonUnknown(err error) bool {
	e := errors.FromError(err)
	return e.Reason == ErrorReason_ERR_REASON_UNKNOWN.String() && e.Code == 500
}

func ErrorErrReasonUnknown(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_ERR_REASON_UNKNOWN.String(), fmt.Sprintf(format, args...))
}

func IsUserNotFound(err error) bool {
	e := errors.FromError(err)
	return e.Reason == ErrorReason_USER_NOT_FOUND.String() && e.Code == 404
}

func ErrorUserNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_USER_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsMissingParameter(err error) bool {
	e := errors.FromError(err)
	return e.Reason == ErrorReason_MISSING_PARAMETER.String() && e.Code == 400
}

func ErrorMissingParameter(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_MISSING_PARAMETER.String(), fmt.Sprintf(format, args...))
}

func IsInternalError(err error) bool {
	e := errors.FromError(err)
	return e.Reason == ErrorReason_INTERNAL_ERROR.String() && e.Code == 500
}

func ErrorInternalError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_INTERNAL_ERROR.String(), fmt.Sprintf(format, args...))
}

func IsUnauthorized(err error) bool {
	e := errors.FromError(err)
	return e.Reason == ErrorReason_Unauthorized.String() && e.Code == 401
}

func ErrorUnauthorized(format string, args ...interface{}) *errors.Error {
	return errors.New(401, ErrorReason_Unauthorized.String(), fmt.Sprintf(format, args...))
}

func IsWrongTokenType(err error) bool {
	e := errors.FromError(err)
	return e.Reason == ErrorReason_WrongTokenType.String() && e.Code == 401
}

func ErrorWrongTokenType(format string, args ...interface{}) *errors.Error {
	return errors.New(401, ErrorReason_WrongTokenType.String(), fmt.Sprintf(format, args...))
}
