// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: types.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MediaType int32

const (
	MediaType_MediaType_UNUSED MediaType = 0
	MediaType_Image            MediaType = 1 // Image, e.g. jpeg, png, gif, bmp
	MediaType_Audio            MediaType = 2 // Audio, e.g. mp3, wav
	MediaType_Video            MediaType = 3 // Video, e.g. mp4, avi
	MediaType_OfficeDocument   MediaType = 4 // office document, e.g. doc, xls, ppt
	MediaType_Other            MediaType = 5
	MediaType_Archive          MediaType = 6 // Compressed file, e.g: .zip, .rar, .7z
	MediaType_ExecutableFile   MediaType = 7 // Executable file, e.g: .exe, .apk, .ipa, .dmg, .jar
	MediaType_Text             MediaType = 8 // Text, e.g: .txt, .log, .md, .xml, .json, csv
	MediaType_PDF              MediaType = 9 // PDF, e.g: .pdf
)

// Enum value maps for MediaType.
var (
	MediaType_name = map[int32]string{
		0: "MediaType_UNUSED",
		1: "Image",
		2: "Audio",
		3: "Video",
		4: "OfficeDocument",
		5: "Other",
		6: "Archive",
		7: "ExecutableFile",
		8: "Text",
		9: "PDF",
	}
	MediaType_value = map[string]int32{
		"MediaType_UNUSED": 0,
		"Image":            1,
		"Audio":            2,
		"Video":            3,
		"OfficeDocument":   4,
		"Other":            5,
		"Archive":          6,
		"ExecutableFile":   7,
		"Text":             8,
		"PDF":              9,
	}
)

func (x MediaType) Enum() *MediaType {
	p := new(MediaType)
	*p = x
	return p
}

func (x MediaType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MediaType) Descriptor() protoreflect.EnumDescriptor {
	return file_types_proto_enumTypes[0].Descriptor()
}

func (MediaType) Type() protoreflect.EnumType {
	return &file_types_proto_enumTypes[0]
}

func (x MediaType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MediaType.Descriptor instead.
func (MediaType) EnumDescriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{0}
}

type MediaStatus int32

const (
	MediaStatus_MediaStatus_UNUSED MediaStatus = 0
	MediaStatus_Valid              MediaStatus = 1
	MediaStatus_InValid            MediaStatus = 2
	MediaStatus_Deleted            MediaStatus = 3
)

// Enum value maps for MediaStatus.
var (
	MediaStatus_name = map[int32]string{
		0: "MediaStatus_UNUSED",
		1: "Valid",
		2: "InValid",
		3: "Deleted",
	}
	MediaStatus_value = map[string]int32{
		"MediaStatus_UNUSED": 0,
		"Valid":              1,
		"InValid":            2,
		"Deleted":            3,
	}
)

func (x MediaStatus) Enum() *MediaStatus {
	p := new(MediaStatus)
	*p = x
	return p
}

func (x MediaStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MediaStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_types_proto_enumTypes[1].Descriptor()
}

func (MediaStatus) Type() protoreflect.EnumType {
	return &file_types_proto_enumTypes[1]
}

func (x MediaStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MediaStatus.Descriptor instead.
func (MediaStatus) EnumDescriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{1}
}

type MediaReasonType int32

const (
	MediaReasonType_MediaReasonType_UNUSED MediaReasonType = 0
	MediaReasonType_Risky                  MediaReasonType = 1 // 违规
	MediaReasonType_UserOpt                MediaReasonType = 2 // 用户自己操作
	MediaReasonType_AuditFailure           MediaReasonType = 3 // 外部平台审核失败, 如上传微信失败等，记录失败原因
)

// Enum value maps for MediaReasonType.
var (
	MediaReasonType_name = map[int32]string{
		0: "MediaReasonType_UNUSED",
		1: "Risky",
		2: "UserOpt",
		3: "AuditFailure",
	}
	MediaReasonType_value = map[string]int32{
		"MediaReasonType_UNUSED": 0,
		"Risky":                  1,
		"UserOpt":                2,
		"AuditFailure":           3,
	}
)

func (x MediaReasonType) Enum() *MediaReasonType {
	p := new(MediaReasonType)
	*p = x
	return p
}

func (x MediaReasonType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MediaReasonType) Descriptor() protoreflect.EnumDescriptor {
	return file_types_proto_enumTypes[2].Descriptor()
}

func (MediaReasonType) Type() protoreflect.EnumType {
	return &file_types_proto_enumTypes[2]
}

func (x MediaReasonType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MediaReasonType.Descriptor instead.
func (MediaReasonType) EnumDescriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{2}
}

type MediaLevel int32

const (
	MediaLevel_MediaLevel_UNUSED MediaLevel = 0
	MediaLevel_General           MediaLevel = 1
	MediaLevel_Sensitive         MediaLevel = 2
)

// Enum value maps for MediaLevel.
var (
	MediaLevel_name = map[int32]string{
		0: "MediaLevel_UNUSED",
		1: "General",
		2: "Sensitive",
	}
	MediaLevel_value = map[string]int32{
		"MediaLevel_UNUSED": 0,
		"General":           1,
		"Sensitive":         2,
	}
)

func (x MediaLevel) Enum() *MediaLevel {
	p := new(MediaLevel)
	*p = x
	return p
}

func (x MediaLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MediaLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_types_proto_enumTypes[3].Descriptor()
}

func (MediaLevel) Type() protoreflect.EnumType {
	return &file_types_proto_enumTypes[3]
}

func (x MediaLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MediaLevel.Descriptor instead.
func (MediaLevel) EnumDescriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{3}
}

type OutUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CompanyId int64 `protobuf:"varint,2,opt,name=company_id,proto3" json:"company_id,omitempty"`
}

func (x *OutUser) Reset() {
	*x = OutUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutUser) ProtoMessage() {}

func (x *OutUser) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutUser.ProtoReflect.Descriptor instead.
func (*OutUser) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{0}
}

func (x *OutUser) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OutUser) GetCompanyId() int64 {
	if x != nil {
		return x.CompanyId
	}
	return 0
}

var File_types_proto protoreflect.FileDescriptor

var file_types_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x22, 0x39, 0x0a, 0x07, 0x4f, 0x75, 0x74, 0x55, 0x73, 0x65, 0x72, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x5f, 0x69, 0x64, 0x2a,
	0x95, 0x01, 0x0a, 0x09, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a,
	0x10, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x55, 0x4e, 0x55, 0x53, 0x45,
	0x44, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x10, 0x01, 0x12, 0x09,
	0x0a, 0x05, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x56, 0x69, 0x64,
	0x65, 0x6f, 0x10, 0x03, 0x12, 0x12, 0x0a, 0x0e, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x44, 0x6f,
	0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x10, 0x04, 0x12, 0x09, 0x0a, 0x05, 0x4f, 0x74, 0x68, 0x65,
	0x72, 0x10, 0x05, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x10, 0x06,
	0x12, 0x12, 0x0a, 0x0e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x46, 0x69,
	0x6c, 0x65, 0x10, 0x07, 0x12, 0x08, 0x0a, 0x04, 0x54, 0x65, 0x78, 0x74, 0x10, 0x08, 0x12, 0x07,
	0x0a, 0x03, 0x50, 0x44, 0x46, 0x10, 0x09, 0x2a, 0x4a, 0x0a, 0x0b, 0x4d, 0x65, 0x64, 0x69, 0x61,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x12, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x55, 0x4e, 0x55, 0x53, 0x45, 0x44, 0x10, 0x00, 0x12, 0x09,
	0x0a, 0x05, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x6e, 0x56,
	0x61, 0x6c, 0x69, 0x64, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x64, 0x10, 0x03, 0x2a, 0x57, 0x0a, 0x0f, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x61, 0x73,
	0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x16, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x55, 0x4e, 0x55, 0x53, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x52, 0x69, 0x73, 0x6b, 0x79, 0x10, 0x01, 0x12, 0x0b, 0x0a,
	0x07, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x70, 0x74, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x41, 0x75,
	0x64, 0x69, 0x74, 0x46, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x10, 0x03, 0x2a, 0x3f, 0x0a, 0x0a,
	0x4d, 0x65, 0x64, 0x69, 0x61, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x15, 0x0a, 0x11, 0x4d, 0x65,
	0x64, 0x69, 0x61, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x5f, 0x55, 0x4e, 0x55, 0x53, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x0b, 0x0a, 0x07, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x10, 0x01, 0x12, 0x0d,
	0x0a, 0x09, 0x53, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x76, 0x65, 0x10, 0x02, 0x42, 0x0b, 0x5a,
	0x09, 0x61, 0x70, 0x70, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_types_proto_rawDescOnce sync.Once
	file_types_proto_rawDescData = file_types_proto_rawDesc
)

func file_types_proto_rawDescGZIP() []byte {
	file_types_proto_rawDescOnce.Do(func() {
		file_types_proto_rawDescData = protoimpl.X.CompressGZIP(file_types_proto_rawDescData)
	})
	return file_types_proto_rawDescData
}

var file_types_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_types_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_types_proto_goTypes = []interface{}{
	(MediaType)(0),       // 0: types.MediaType
	(MediaStatus)(0),     // 1: types.MediaStatus
	(MediaReasonType)(0), // 2: types.MediaReasonType
	(MediaLevel)(0),      // 3: types.MediaLevel
	(*OutUser)(nil),      // 4: types.OutUser
}
var file_types_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_types_proto_init() }
func file_types_proto_init() {
	if File_types_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_types_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OutUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_types_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_proto_goTypes,
		DependencyIndexes: file_types_proto_depIdxs,
		EnumInfos:         file_types_proto_enumTypes,
		MessageInfos:      file_types_proto_msgTypes,
	}.Build()
	File_types_proto = out.File
	file_types_proto_rawDesc = nil
	file_types_proto_goTypes = nil
	file_types_proto_depIdxs = nil
}
